from flask import send_file, send_from_directory, render_template, redirect, url_for


def add_data_to_database(driver):
    # Vérifiez si la base de données est vide avant d'ajouter des données
        # Ajoutez les employés et les relations avec les départements
        check_result = driver.execute_query("MATCH (n) RETURN count(n) as Match_Count")
         
        print("check_result",check_result)
        result = check_result.records
        count = result[0]["Match_Count"]

        if count == 0:
            cypher_query = """   
            // Employés 
            CREATE (John:EMPLOYEE {name: "John Doe", Dept: "IT", role: "Developer", manager: "Manager1", salary: 60000})
            CREATE (Jane:EMPLOYEE {name: "Jane Smith", Dept: "HR", role: "HR Specialist", manager: "Manager2", salary: 55000})
            CREATE (Bob:EMPLOYEE {name: "Bob Johnson", Dept: "Finance", role: "Accountant", manager: "Manager3", salary: 65000})
            CREATE (Alice:EMPLOYEE {name: "Alice Dupont", Dept: "Data", role: "Data Scientist", manager: "Manager4", salary: 70000})
            CREATE (Charlie:EMPLOYEE {name: "Charlie Martin", Dept: "Cyber security", role: "Security Analyst", manager: "Manager5", salary: 75000})
            CREATE (Employee6:EMPLOYEE {name: "Emma Tremblay", Dept: "Marketing", role: "Marketing Specialist", manager: "Manager6", salary: 62000})
            CREATE (Employee7:EMPLOYEE {name: "Louis Lefevre", Dept: "Operations", role: "Operations Manager", manager: "Manager7", salary: 70000})
            CREATE (Employee8:EMPLOYEE {name: "Sophie Gagnon", Dept: "Sales", role: "Sales Representative", manager: "Manager8", salary: 58000})
            CREATE (Employee9:EMPLOYEE {name: "Thomas Bernard", Dept: "Research", role: "Research Scientist", manager: "Manager9", salary: 72000})
            CREATE (Employee10:EMPLOYEE {name: "Claire Martin", Dept: "Legal", role: "Legal Counsel", manager: "Manager10", salary: 80000})
            CREATE (Employee11:EMPLOYEE {name: "Pierre Dubois", Dept: "IT", role: "System Analyst", manager: "Manager1", salary: 67000})
            CREATE (Employee12:EMPLOYEE {name: "Isabelle Lavoie", Dept: "Finance", role: "Financial Planner", manager: "Manager3", salary: 64000})
            CREATE (Employee13:EMPLOYEE {name: "Alexandre Girard", Dept: "HR", role: "Training Coordinator", manager: "Manager2", salary: 60000})
            CREATE (Employee14:EMPLOYEE {name: "Camille Roy", Dept: "Marketing", role: "Brand Manager", manager: "Manager6", salary: 69000})
            CREATE (Employee15:EMPLOYEE {name: "Mathieu Lévesque", Dept: "Operations", role: "Supply Chain Analyst", manager: "Manager7", salary: 71000})
            CREATE (Employee16:EMPLOYEE {name: "Marie-Claire Bergeron", Dept: "Legal", role: "Legal Assistant", manager: "Manager10", salary: 55000})
            CREATE (Employee17:EMPLOYEE {name: "Guillaume Tremblay", Dept: "Sales", role: "Sales Manager", manager: "Manager8", salary: 72000})
            CREATE (Employee18:EMPLOYEE {name: "Aurélie Boucher", Dept: "Research", role: "Research Assistant", manager: "Manager9", salary: 59000})
            CREATE (Employee19:EMPLOYEE {name: "Daniel Martin", Dept: "IT", role: "Database Administrator", manager: "Manager1", salary: 68000})
            CREATE (Employee20:EMPLOYEE {name: "Valérie Gagné", Dept: "Marketing", role: "Event Coordinator", manager: "Manager6", salary: 63000})
            CREATE (Employee21:EMPLOYEE {name: "Philippe Lefebvre", Dept: "Finance", role: "Financial Analyst", manager: "Manager3", salary: 62000})
            CREATE (Employee22:EMPLOYEE {name: "Catherine Moreau", Dept: "IT", role: "Software Engineer", manager: "Manager1", salary: 70000})
            CREATE (Employee23:EMPLOYEE {name: "Luc Deschamps", Dept: "HR", role: "HR Generalist", manager: "Manager2", salary: 59000})
            CREATE (Employee24:EMPLOYEE {name: "Julie Gauthier", Dept: "Legal", role: "Corporate Counsel", manager: "Manager10", salary: 75000})
            CREATE (Employee25:EMPLOYEE {name: "Alexis Dubois", Dept: "Sales", role: "Account Executive", manager: "Manager8", salary: 66000})
            CREATE (Employee26:EMPLOYEE {name: "Émilie Lavoie", Dept: "Research", role: "Research Scientist", manager: "Manager9", salary: 72000})
            CREATE (Employee27:EMPLOYEE {name: "Olivier Girard", Dept: "Marketing", role: "Marketing Coordinator", manager: "Manager6", salary: 60000})
            CREATE (Employee28:EMPLOYEE {name: "Sophie Bélanger", Dept: "Cybersecurity", role: "Security Consultant", manager: "Manager5", salary: 80000})
            CREATE (Employee29:EMPLOYEE {name: "Maxime Rochon", Dept: "Operations", role: "Operations Coordinator", manager: "Manager7", salary: 65000})
            CREATE (Employee32:EMPLOYEE {name: "Chloé Lavoie", Dept: "Finance", role: "Financial Analyst", manager: "Manager3", salary: 62000})
            CREATE (Employee33:EMPLOYEE {name: "Vincent Gagnon", Dept: "HR", role: "HR Coordinator", manager: "Manager2", salary: 58000})
            CREATE (Employee34:EMPLOYEE {name: "Stéphanie Dubois", Dept: "Legal", role: "Legal Assistant", manager: "Manager10", salary: 55000})
            CREATE (Employee35:EMPLOYEE {name: "Nicolas Martin", Dept: "Sales", role: "Sales Representative", manager: "Manager8", salary: 68000})
            CREATE (Employee36:EMPLOYEE {name: "Caroline Tremblay", Dept: "Research", role: "Research Scientist", manager: "Manager9", salary: 72000})
            CREATE (Employee37:EMPLOYEE {name: "Alexandre Gauthier", Dept: "Marketing", role: "Marketing Specialist", manager: "Manager6", salary: 60000})
            CREATE (Employee38:EMPLOYEE {name: "Isabelle Boucher", Dept: "Cybersecurity", role: "Security Analyst", manager: "Manager5", salary: 75000})
            CREATE (Employee39:EMPLOYEE {name: "Frédéric Rochon", Dept: "Operations", role: "Operations Manager", manager: "Manager7", salary: 70000})
            CREATE (Employee40:EMPLOYEE {name: "Mélanie Lévesque", Dept: "Data", role: "Data Analyst", manager: "Manager4", salary: 67000})
            CREATE (Employee41:EMPLOYEE {name: "Martin Dubé", Dept: "IT", role: "Database Administrator", manager: "Manager1", salary: 69000})
            CREATE (Employee42:EMPLOYEE {name: "Valérie Gagné", Dept: "Finance", role: "Financial Planner", manager: "Manager3", salary: 64000})
            CREATE (Employee43:EMPLOYEE {name: "Jeanne Tremblay", Dept: "HR", role: "HR Generalist", manager: "Manager2", salary: 59000})
            CREATE (Employee44:EMPLOYEE {name: "Éric Lavoie", Dept: "Legal", role: "Corporate Counsel", manager: "Manager10", salary: 78000})
            CREATE (Employee45:EMPLOYEE {name: "Marie-Claude Bélanger", Dept: "Sales", role: "Account Executive", manager: "Manager8", salary: 70000})
            CREATE (Employee46:EMPLOYEE {name: "Patrick Roy", Dept: "Research", role: "Research Assistant", manager: "Manager9", salary: 60000})
            CREATE (Employee47:EMPLOYEE {name: "Sophie Gagnon", Dept: "Marketing", role: "Marketing Coordinator", manager: "Manager6", salary: 62000})
            CREATE (Employee48:EMPLOYEE {name: "François Girard", Dept: "Cybersecurity", role: "Security Consultant", manager: "Manager5", salary: 80000})
            CREATE (Employee49:EMPLOYEE {name: "Véronique Rochon", Dept: "Operations", role: "Operations Coordinator", manager: "Manager7", salary: 65000})
            CREATE (Employee50:EMPLOYEE {name: "Michel Martin", Dept: "Data", role: "Data Scientist", manager: "Manager4", salary: 71000})
            CREATE (Employee51:EMPLOYEE {name: "Hélène Dubois", Dept: "IT", role: "System Administrator", manager: "Manager1", salary: 68000})
            CREATE (Employee52:EMPLOYEE {name: "Sébastien Lefebvre", Dept: "Finance", role: "Financial Analyst", manager: "Manager3", salary: 62000})
            CREATE (Employee53:EMPLOYEE {name: "Julie Martin", Dept: "HR", role: "Training Coordinator", manager: "Manager2", salary: 60000})
            CREATE (Employee54:EMPLOYEE {name: "Maxime Gagnon", Dept: "Legal", role: "Legal Assistant", manager: "Manager10", salary: 55000})
            CREATE (Employee55:EMPLOYEE {name: "Catherine Dubois", Dept: "Sales", role: "Sales Manager", manager: "Manager8", salary: 72000})
            CREATE (Employee56:EMPLOYEE {name: "Pierre Lavoie", Dept: "Research", role: "Research Scientist", manager: "Manager9", salary: 75000})
            CREATE (Employee57:EMPLOYEE {name: "Caroline Gauthier", Dept: "Marketing", role: "Marketing Coordinator", manager: "Manager6", salary: 60000})
            CREATE (Employee58:EMPLOYEE {name: "Nicolas Boucher", Dept: "Cybersecurity", role: "Security Consultant", manager: "Manager5", salary: 80000})
            CREATE (Employee59:EMPLOYEE {name: "Valérie Rochon", Dept: "Operations", role: "Operations Coordinator", manager: "Manager7", salary: 65000})
            CREATE (Employee60:EMPLOYEE {name: "David Martin", Dept: "Data", role: "Data Analyst", manager: "Manager4", salary: 67000})
            CREATE (Employee61:EMPLOYEE {name: "Marie-Josée Martin", Dept: "IT", role: "Network Administrator", manager: "Manager1", salary: 70000})
            CREATE (Employee62:EMPLOYEE {name: "Gabriel Dubois", Dept: "Finance", role: "Financial Analyst", manager: "Manager3", salary: 64000})
            CREATE (Employee63:EMPLOYEE {name: "Isabelle Gagnon", Dept: "HR", role: "HR Specialist", manager: "Manager2", salary: 60000})
            CREATE (Employee64:EMPLOYEE {name: "Lucie Tremblay", Dept: "Legal", role: "Legal Assistant", manager: "Manager10", salary: 56000})
            CREATE (Employee65:EMPLOYEE {name: "Étienne Lavoie", Dept: "Sales", role: "Sales Representative", manager: "Manager8", salary: 68000})
            CREATE (Employee66:EMPLOYEE {name: "Catherine Martin", Dept: "Research", role: "Research Scientist", manager: "Manager9", salary: 73000})
            CREATE (Employee67:EMPLOYEE {name: "Patrick Gauthier", Dept: "Marketing", role: "Marketing Coordinator", manager: "Manager6", salary: 62000})
            CREATE (Employee68:EMPLOYEE {name: "Sylvie Boucher", Dept: "Cybersecurity", role: "Security Analyst", manager: "Manager5", salary: 76000})
            CREATE (Employee69:EMPLOYEE {name: "François Rochon", Dept: "Operations", role: "Operations Manager", manager: "Manager7", salary: 71000})
            CREATE (Employee70:EMPLOYEE {name: "Sophie Martin", Dept: "Data", role: "Data Analyst", manager: "Manager4", salary: 69000})
            CREATE (Employee71:EMPLOYEE {name: "Michel Dubé", Dept: "IT", role: "Database Administrator", manager: "Manager1", salary: 72000})
            CREATE (Employee72:EMPLOYEE {name: "Nathalie Gagné", Dept: "Finance", role: "Financial Planner", manager: "Manager3", salary: 65000})
            CREATE (Employee73:EMPLOYEE {name: "Martin Lefebvre", Dept: "HR", role: "HR Generalist", manager: "Manager2", salary: 59000})
            CREATE (Employee74:EMPLOYEE {name: "Geneviève Tremblay", Dept: "Legal", role: "Corporate Counsel", manager: "Manager10", salary: 77000})
            CREATE (Employee75:EMPLOYEE {name: "Sébastien Martin", Dept: "Sales", role: "Account Executive", manager: "Manager8", salary: 70000})
            CREATE (Employee76:EMPLOYEE {name: "Émilie Gauthier", Dept: "Research", role: "Research Assistant", manager: "Manager9", salary: 63000})
            CREATE (Employee77:EMPLOYEE {name: "David Boucher", Dept: "Marketing", role: "Marketing Specialist", manager: "Manager6", salary: 61000})
            CREATE (Employee78:EMPLOYEE {name: "Julie Rochon", Dept: "Cybersecurity", role: "Security Consultant", manager: "Manager5", salary: 79000})
            CREATE (Employee79:EMPLOYEE {name: "Simon Lavoie", Dept: "Operations", role: "Operations Coordinator", manager: "Manager7", salary: 67000})
            CREATE (Employee80:EMPLOYEE {name: "Élise Martin", Dept: "Data", role: "Data Scientist", manager: "Manager4", salary: 73000})

        
            


        
            
    

            
            


            // Départements
            CREATE (DepartmentMarketing:DEPARTMENT {name: "Marketing", description: "Marketing Department"})
            CREATE (DepartmentOperations:DEPARTMENT {name: "Operations", description: "Operations Department"})
            CREATE (DepartmentSales:DEPARTMENT {name: "Sales", description: "Sales Department"})
            CREATE (DepartmentResearch:DEPARTMENT {name: "Research", description: "Research Department"})
            CREATE (DepartmentLegal:DEPARTMENT {name: "Legal", description: "Legal Department"})
            CREATE (departmentIT:DEPARTMENT {name: "IT",description:"IT Department"})
            CREATE (departmentHR:DEPARTMENT {name: "HR",description:"HR Department"})
            CREATE (departmentFinance:DEPARTMENT {name: "Finance",description:"Finance Department"})
            CREATE (departmentData:DEPARTMENT {name: "Data",description:"Data Department"})
            CREATE (departmentCybersecurity:DEPARTMENT {name: "Cyber security",description:"Cyber security Department"})



            // Relations Employé-Département supplémentaires
            CREATE (John)-[:WORKS_IN]->(departmentIT)
            CREATE (Jane)-[:WORKS_IN]->(departmentHR)
            CREATE (Bob)-[:WORKS_IN]->(departmentFinance)
            CREATE (Alice)-[:WORKS_IN]->(departmentData)
            CREATE (Charlie)-[:WORKS_IN]->(departmentCybersecurity)
            CREATE (Employee6)-[:WORKS_IN]->(DepartmentMarketing)
            CREATE (Employee7)-[:WORKS_IN]->(DepartmentOperations)
            CREATE (Employee8)-[:WORKS_IN]->(DepartmentSales)
            CREATE (Employee9)-[:WORKS_IN]->(DepartmentResearch)
            CREATE (Employee10)-[:WORKS_IN]->(DepartmentLegal)
            CREATE (Employee11)-[:WORKS_IN]->(DepartmentIT)
            CREATE (Employee12)-[:WORKS_IN]->(DepartmentFinance)
            CREATE (Employee13)-[:WORKS_IN]->(DepartmentHR)
            CREATE (Employee14)-[:WORKS_IN]->(DepartmentMarketing)
            CREATE (Employee15)-[:WORKS_IN]->(DepartmentOperations)
            CREATE (Employee16)-[:WORKS_IN]->(DepartmentLegal)
            CREATE (Employee17)-[:WORKS_IN]->(DepartmentSales)
            CREATE (Employee18)-[:WORKS_IN]->(DepartmentResearch)
            CREATE (Employee19)-[:WORKS_IN]->(DepartmentIT)
            CREATE (Employee20)-[:WORKS_IN]->(DepartmentMarketing)
            CREATE (Employee21)-[:WORKS_IN]->(DepartmentFinance)
            CREATE (Employee22)-[:WORKS_IN]->(DepartmentIT)
            CREATE (Employee23)-[:WORKS_IN]->(DepartmentHR)
            CREATE (Employee24)-[:WORKS_IN]->(DepartmentLegal)
            CREATE (Employee25)-[:WORKS_IN]->(DepartmentSales)
            CREATE (Employee26)-[:WORKS_IN]->(DepartmentResearch)
            CREATE (Employee27)-[:WORKS_IN]->(DepartmentMarketing)
            CREATE (Employee28)-[:WORKS_IN]->(DepartmentCybersecurity)
            CREATE (Employee29)-[:WORKS_IN]->(DepartmentOperations)
            CREATE (Employee32)-[:WORKS_IN]->(DepartmentFinance)
            CREATE (Employee33)-[:WORKS_IN]->(DepartmentHR)
            CREATE (Employee34)-[:WORKS_IN]->(DepartmentLegal)
            CREATE (Employee35)-[:WORKS_IN]->(DepartmentSales)
            CREATE (Employee36)-[:WORKS_IN]->(DepartmentResearch)
            CREATE (Employee37)-[:WORKS_IN]->(DepartmentMarketing)
            CREATE (Employee38)-[:WORKS_IN]->(DepartmentCybersecurity)
            CREATE (Employee39)-[:WORKS_IN]->(DepartmentOperations)
            CREATE (Employee40)-[:WORKS_IN]->(DepartmentData)
            CREATE (Employee41)-[:WORKS_IN]->(DepartmentIT)
            CREATE (Employee42)-[:WORKS_IN]->(DepartmentFinance)
            CREATE (Employee43)-[:WORKS_IN]->(DepartmentHR)
            CREATE (Employee44)-[:WORKS_IN]->(DepartmentLegal)
            CREATE (Employee45)-[:WORKS_IN]->(DepartmentSales)
            CREATE (Employee46)-[:WORKS_IN]->(DepartmentResearch)
            CREATE (Employee47)-[:WORKS_IN]->(DepartmentMarketing)
            CREATE (Employee48)-[:WORKS_IN]->(DepartmentCybersecurity)
            CREATE (Employee49)-[:WORKS_IN]->(DepartmentOperations)
            CREATE (Employee50)-[:WORKS_IN]->(DepartmentData)
            CREATE (Employee51)-[:WORKS_IN]->(DepartmentIT)
            CREATE (Employee52)-[:WORKS_IN]->(DepartmentFinance)
            CREATE (Employee53)-[:WORKS_IN]->(DepartmentHR)
            CREATE (Employee54)-[:WORKS_IN]->(DepartmentLegal)
            CREATE (Employee55)-[:WORKS_IN]->(DepartmentSales)
            CREATE (Employee56)-[:WORKS_IN]->(DepartmentResearch)
            CREATE (Employee57)-[:WORKS_IN]->(DepartmentMarketing)
            CREATE (Employee58)-[:WORKS_IN]->(DepartmentCybersecurity)
            CREATE (Employee59)-[:WORKS_IN]->(DepartmentOperations)
            CREATE (Employee60)-[:WORKS_IN]->(DepartmentData)
            CREATE (Employee61)-[:WORKS_IN]->(DepartmentIT)
            CREATE (Employee62)-[:WORKS_IN]->(DepartmentFinance)
            CREATE (Employee63)-[:WORKS_IN]->(DepartmentHR)
            CREATE (Employee64)-[:WORKS_IN]->(DepartmentLegal)
            CREATE (Employee65)-[:WORKS_IN]->(DepartmentSales)
            CREATE (Employee66)-[:WORKS_IN]->(DepartmentResearch)
            CREATE (Employee67)-[:WORKS_IN]->(DepartmentMarketing)
            CREATE (Employee68)-[:WORKS_IN]->(DepartmentCybersecurity)
            CREATE (Employee69)-[:WORKS_IN]->(DepartmentOperations)
            CREATE (Employee70)-[:WORKS_IN]->(DepartmentData)
            CREATE (Employee71)-[:WORKS_IN]->(DepartmentIT)
            CREATE (Employee72)-[:WORKS_IN]->(DepartmentFinance)
            CREATE (Employee73)-[:WORKS_IN]->(DepartmentHR)
            CREATE (Employee74)-[:WORKS_IN]->(DepartmentLegal)
            CREATE (Employee75)-[:WORKS_IN]->(DepartmentSales)
            CREATE (Employee76)-[:WORKS_IN]->(DepartmentResearch)
            CREATE (Employee77)-[:WORKS_IN]->(DepartmentMarketing)
            CREATE (Employee78)-[:WORKS_IN]->(DepartmentCybersecurity)
            CREATE (Employee79)-[:WORKS_IN]->(DepartmentOperations)
            CREATE (Employee80)-[:WORKS_IN]->(DepartmentData)


            """
            driver.execute_query(cypher_query)
            print("Données ajoutées avec succès !")
